export { default as Dashboard } from "./dashboard";
export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as NotFound } from "./not-found";
export { default as Settings } from "./settings";
export { default as Cases } from "./cases";
export { default as Lawyers } from "./lawyers";
export { default as Users } from "./users";
export { default as User } from "./user";
